version: '3.8'
services:
  mysql:
    image: mysql:8.3
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: financialsolutions
      MYSQL_USER: fsuser
      MYSQL_PASSWORD: fspassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql-db;Port=3306;Database=financialsolutions;User=fsuser;Password=fspassword;

  moneytransfer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moneytransfer-app
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql-db;Port=3306;Database=financialsolutions;User=fsuser;Password=fspassword;
      - MYSQL_HOST=mysql-db
      - MYSQL_USER=fsuser
      - MYSQL_PASSWORD=fspassword
    ports:
      - "5000:8080"
    restart: always

volumes:
  mysql-data:
