version: '3.8'
services:
  mysql:
    image: mysql:8.3
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: financialsolutions
      MYSQL_USER: fsuser
      MYSQL_PASSWORD: fspassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:

